apiVersion: v1
kind: Service
metadata:
  name: iam-accesskey-finder
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: iam-accesskey-finder
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
